// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: lvglUITest

#include "../ui.h"


// COMPONENT buttonLabel

lv_obj_t * ui_buttonLabel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_buttonLabel;
    cui_buttonLabel = lv_label_create(comp_parent);
    lv_obj_set_width(cui_buttonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_buttonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_buttonLabel, 1);
    lv_obj_set_y(cui_buttonLabel, 1);
    lv_obj_set_align(cui_buttonLabel, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONLABEL_NUM);
    children[UI_COMP_BUTTONLABEL_BUTTONLABEL] = cui_buttonLabel;
    lv_obj_add_event_cb(cui_buttonLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_buttonLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_buttonLabel_create_hook(cui_buttonLabel);
    return cui_buttonLabel;
}

