// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: lvglUITest

#ifndef _UI_COMP_BUTTONLABEL_H
#define _UI_COMP_BUTTONLABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT buttonLabel
#define UI_COMP_BUTTONLABEL_BUTTONLABEL 0
#define _UI_COMP_BUTTONLABEL_NUM 1
lv_obj_t * ui_buttonLabel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
