// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_PANELROOMCOMPONENT_H
#define _UI_COMP_PANELROOMCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelroomComponent
#define UI_COMP_PANELROOMCOMPONENT_PANELROOMCOMPONENT 0
#define UI_COMP_PANELROOMCOMPONENT_LABEL_DUMMY_1 1
#define UI_COMP_PANELROOMCOMPONENT_LABEL_DUMMY_2 2
#define UI_COMP_PANELROOMCOMPONENT_BUTTON_GOTO_ROOM 3
#define UI_COMP_PANELROOMCOMPONENT_BUTTON_GOTO_ROOM_LABEL_DUMMY_3 4
#define UI_COMP_PANELROOMCOMPONENT_ROOMID 5
#define UI_COMP_PANELROOMCOMPONENT_ROOM_NUMBERS 6
#define _UI_COMP_PANELROOMCOMPONENT_NUM 7
lv_obj_t * ui_PanelroomComponent_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
