// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT PanelroomComponent

lv_obj_t * ui_PanelroomComponent_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PanelroomComponent;
    cui_PanelroomComponent = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_PanelroomComponent, 480);
    lv_obj_set_height(cui_PanelroomComponent, 50);
    lv_obj_set_align(cui_PanelroomComponent, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(cui_PanelroomComponent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label_dummy_1;
    cui_Label_dummy_1 = lv_label_create(cui_PanelroomComponent);
    lv_obj_set_width(cui_Label_dummy_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_dummy_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_dummy_1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label_dummy_1, "房间号");
    lv_obj_set_style_text_font(cui_Label_dummy_1, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_dummy_2;
    cui_Label_dummy_2 = lv_label_create(cui_PanelroomComponent);
    lv_obj_set_width(cui_Label_dummy_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_dummy_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_dummy_2, 130);
    lv_obj_set_y(cui_Label_dummy_2, 0);
    lv_obj_set_align(cui_Label_dummy_2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label_dummy_2, "房间人数");
    lv_obj_set_style_text_font(cui_Label_dummy_2, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button_goto_room;
    cui_Button_goto_room = lv_btn_create(cui_PanelroomComponent);
    lv_obj_set_width(cui_Button_goto_room, 100);
    lv_obj_set_height(cui_Button_goto_room, 40);
    lv_obj_set_align(cui_Button_goto_room, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Button_goto_room, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button_goto_room, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label_dummy_3;
    cui_Label_dummy_3 = lv_label_create(cui_Button_goto_room);
    lv_obj_set_width(cui_Label_dummy_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_dummy_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_dummy_3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_dummy_3, "加入");
    lv_obj_set_style_text_font(cui_Label_dummy_3, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_RoomID;
    cui_RoomID = lv_label_create(cui_PanelroomComponent);
    lv_obj_set_width(cui_RoomID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_RoomID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_RoomID, 60);
    lv_obj_set_y(cui_RoomID, 0);
    lv_obj_set_align(cui_RoomID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_RoomID, "roomID");
    lv_obj_set_style_text_color(cui_RoomID, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_RoomID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_RoomID, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Room_Numbers;
    cui_Room_Numbers = lv_label_create(cui_PanelroomComponent);
    lv_obj_set_width(cui_Room_Numbers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Room_Numbers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Room_Numbers, 220);
    lv_obj_set_y(cui_Room_Numbers, 0);
    lv_obj_set_align(cui_Room_Numbers, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Room_Numbers, "Userdummy");
    lv_obj_set_style_text_color(cui_Room_Numbers, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Room_Numbers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Room_Numbers, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANELROOMCOMPONENT_NUM);
    children[UI_COMP_PANELROOMCOMPONENT_PANELROOMCOMPONENT] = cui_PanelroomComponent;
    children[UI_COMP_PANELROOMCOMPONENT_LABEL_DUMMY_1] = cui_Label_dummy_1;
    children[UI_COMP_PANELROOMCOMPONENT_LABEL_DUMMY_2] = cui_Label_dummy_2;
    children[UI_COMP_PANELROOMCOMPONENT_BUTTON_GOTO_ROOM] = cui_Button_goto_room;
    children[UI_COMP_PANELROOMCOMPONENT_BUTTON_GOTO_ROOM_LABEL_DUMMY_3] = cui_Label_dummy_3;
    children[UI_COMP_PANELROOMCOMPONENT_ROOMID] = cui_RoomID;
    children[UI_COMP_PANELROOMCOMPONENT_ROOM_NUMBERS] = cui_Room_Numbers;
    lv_obj_add_event_cb(cui_PanelroomComponent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PanelroomComponent, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_PanelroomComponent_create_hook(cui_PanelroomComponent);
    return cui_PanelroomComponent;
}

