// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen_login
void ui_Screen_login_screen_init(void);
lv_obj_t * ui_Screen_login;
lv_obj_t * ui_Container_login_menu;
void ui_event_Username_login(lv_event_t * e);
lv_obj_t * ui_Username_login;
void ui_event_Password_login(lv_event_t * e);
lv_obj_t * ui_Password_login;
void ui_event_Button_login(lv_event_t * e);
lv_obj_t * ui_Button_login;
lv_obj_t * ui_Label_dummy;
void ui_event_Button_go_register(lv_event_t * e);
lv_obj_t * ui_Button_go_register;
lv_obj_t * ui_Label_dummy1;
lv_obj_t * ui_label_login_title;
lv_obj_t * ui_Keyboard_login;
lv_obj_t * ui_Container_login_success;
lv_obj_t * ui_Panel_login_success;
lv_obj_t * ui_Label_login_success;
lv_obj_t * ui_Container_login_fail;
lv_obj_t * ui_Panel_login_fail;
lv_obj_t * ui_Label_login_fail;


// SCREEN: ui_Screen_register
void ui_Screen_register_screen_init(void);
lv_obj_t * ui_Screen_register;
lv_obj_t * ui_Container_register_menu;
void ui_event_Username_register(lv_event_t * e);
lv_obj_t * ui_Username_register;
void ui_event_Password_register(lv_event_t * e);
lv_obj_t * ui_Password_register;
void ui_event_Button_register(lv_event_t * e);
lv_obj_t * ui_Button_register;
lv_obj_t * ui_Label_dummy3;
lv_obj_t * ui_Label_register_title;
lv_obj_t * ui_Keyboard_register;
void ui_event_Button_back_login_screen(lv_event_t * e);
lv_obj_t * ui_Button_back_login_screen;
lv_obj_t * ui_Label_dummy4;


// SCREEN: ui_Screen_main_menu
void ui_Screen_main_menu_screen_init(void);
lv_obj_t * ui_Screen_main_menu;
lv_obj_t * ui_Container_screen_main_menu;
lv_obj_t * ui_Label3;
void ui_event_Button_back_login_screen2(lv_event_t * e);
lv_obj_t * ui_Button_back_login_screen2;
lv_obj_t * ui_Label_dummy5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label6;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Username_login(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard_login, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard_login,  ui_Username_login);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard_login, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Password_login(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard_login, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard_login,  ui_Password_login);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard_login, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button_login(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        User_login(e);
    }
}
void ui_event_Button_go_register(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_register, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_register_screen_init);
    }
}
void ui_event_Username_register(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard_register, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard_register,  ui_Username_register);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard_register, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Password_register(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard_register, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard_register,  ui_Password_register);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard_register, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button_register(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        User_register(e);
    }
}
void ui_event_Button_back_login_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_login, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_login_screen_init);
    }
}
void ui_event_Button_back_login_screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_login, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_login_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_login_screen_init();
    ui_Screen_register_screen_init();
    ui_Screen_main_menu_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_login);
}
