// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen_login
void ui_Screen_login_screen_init(void);
void ui_event_Screen_login(lv_event_t * e);
extern lv_obj_t * ui_Screen_login;
extern lv_obj_t * ui_Container_login_menu;
void ui_event_Username_login(lv_event_t * e);
extern lv_obj_t * ui_Username_login;
void ui_event_Password_login(lv_event_t * e);
extern lv_obj_t * ui_Password_login;
void ui_event_Button_login(lv_event_t * e);
extern lv_obj_t * ui_Button_login;
extern lv_obj_t * ui_Label_dummy;
void ui_event_Button_go_register(lv_event_t * e);
extern lv_obj_t * ui_Button_go_register;
extern lv_obj_t * ui_Label_dummy1;
extern lv_obj_t * ui_label_login_title;
extern lv_obj_t * ui_Keyboard_login;
extern lv_obj_t * ui_Container_login_success;
extern lv_obj_t * ui_Panel_login_success;
extern lv_obj_t * ui_Label_login_success;
extern lv_obj_t * ui_Container_login_fail;
extern lv_obj_t * ui_Panel_login_fail;
extern lv_obj_t * ui_Label_login_fail;
// SCREEN: ui_Screen_register
void ui_Screen_register_screen_init(void);
void ui_event_Screen_register(lv_event_t * e);
extern lv_obj_t * ui_Screen_register;
extern lv_obj_t * ui_Container_register_menu;
void ui_event_Username_register(lv_event_t * e);
extern lv_obj_t * ui_Username_register;
void ui_event_Password_register(lv_event_t * e);
extern lv_obj_t * ui_Password_register;
void ui_event_Button_register(lv_event_t * e);
extern lv_obj_t * ui_Button_register;
extern lv_obj_t * ui_Label_dummy3;
extern lv_obj_t * ui_Label_register_title;
extern lv_obj_t * ui_Keyboard_register;
void ui_event_Button_back_login_screen(lv_event_t * e);
extern lv_obj_t * ui_Button_back_login_screen;
extern lv_obj_t * ui_Label_dummy4;
extern lv_obj_t * ui_Container_register_success;
extern lv_obj_t * ui_Panel_register_success;
extern lv_obj_t * ui_Label_register_success;
extern lv_obj_t * ui_Container_register_fail;
extern lv_obj_t * ui_Panel_register_fail;
extern lv_obj_t * ui_Label_register_fail;
// SCREEN: ui_Screen_main_menu
void ui_Screen_main_menu_screen_init(void);
extern lv_obj_t * ui_Screen_main_menu;
extern lv_obj_t * ui_Container_screen_main_menu;
extern lv_obj_t * ui_Label3;
void ui_event_Button_back_login_screen2(lv_event_t * e);
extern lv_obj_t * ui_Button_back_login_screen2;
extern lv_obj_t * ui_Label_dummy5;
extern lv_obj_t * ui_Panel_room_info;
void ui_event_Button_creat_room(lv_event_t * e);
extern lv_obj_t * ui_Button_creat_room;
extern lv_obj_t * ui_Label_dummy_1;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_Screen_room
void ui_Screen_room_screen_init(void);
extern lv_obj_t * ui_Screen_room;
extern lv_obj_t * ui_Container_screen_main_menu1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
void ui_event_Button_exit_room(lv_event_t * e);
extern lv_obj_t * ui_Button_exit_room;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen_match
void ui_Screen_match_screen_init(void);
extern lv_obj_t * ui_Screen_match;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image_chessboard;
extern lv_obj_t * ui_Image_Chess_King_Black;
extern lv_obj_t * ui_Image_Mandarins_Black_Left;
extern lv_obj_t * ui_Image_Mandarins_Black_Right;
extern lv_obj_t * ui_Image_Elephants_Black_Left;
extern lv_obj_t * ui_Image_Elephants_Black_Right;
extern lv_obj_t * ui_Image_Knights_Black_Left;
extern lv_obj_t * ui_Image_Knights_Black_Right;
extern lv_obj_t * ui_Image_Rooks_Black_Left;
extern lv_obj_t * ui_Image_Rooks_Black_Right;
extern lv_obj_t * ui_Image_Cannons_Black_Left;
extern lv_obj_t * ui_Image_Cannons_Black_Right;
extern lv_obj_t * ui_Image_Pawns_Black1;
extern lv_obj_t * ui_Image_Pawns_Black2;
extern lv_obj_t * ui_Image_Pawns_Black3;
extern lv_obj_t * ui_Image_Pawns_Black4;
extern lv_obj_t * ui_Image_Pawns_Black5;
extern lv_obj_t * ui_Image_General_Red;
extern lv_obj_t * ui_Image_Image_Mandarins_Red_Left;
extern lv_obj_t * ui_Image_Image_Mandarins_Red_Right;
extern lv_obj_t * ui_Image_Elephants_Red_Left;
extern lv_obj_t * ui_Image_Elephants_Red_Right;
extern lv_obj_t * ui_Image_Knights_Red_Left;
extern lv_obj_t * ui_Image_Knights_Red_Right;
extern lv_obj_t * ui_Image_Rooks_Red_Left;
extern lv_obj_t * ui_Image_Rooks_Red_Right;
extern lv_obj_t * ui_Image_Cannons_Red_Left;
extern lv_obj_t * ui_Image_Cannons_Red_Right;
extern lv_obj_t * ui_Image_Pawns_Red1;
extern lv_obj_t * ui_Image_Pawns_Red2;
extern lv_obj_t * ui_Image_Pawns_Red3;
extern lv_obj_t * ui_Image_Pawns_Red4;
extern lv_obj_t * ui_Image_Pawns_Red5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_chessboard_png);    // assets/Chessboard.png
LV_IMG_DECLARE(ui_img_chess_king_black_png);    // assets/Chess_king_Black.png
LV_IMG_DECLARE(ui_img_chess_mandarins_black_png);    // assets/Chess_Mandarins_Black.png
LV_IMG_DECLARE(ui_img_chess_elephants_black_png);    // assets/Chess_Elephants_Black.png
LV_IMG_DECLARE(ui_img_chess_knights_black_png);    // assets/Chess_Knights_Black.png
LV_IMG_DECLARE(ui_img_chess_rooks_black_png);    // assets/Chess_Rooks_Black.png
LV_IMG_DECLARE(ui_img_chess_cannons_black_png);    // assets/Chess_Cannons_Black.png
LV_IMG_DECLARE(ui_img_chess_pawns_black_png);    // assets/Chess_Pawns_Black.png
LV_IMG_DECLARE(ui_img_chess_general_red_png);    // assets/Chess_General_Red.png
LV_IMG_DECLARE(ui_img_chess_mandarins_red_png);    // assets/Chess_Mandarins_Red.png
LV_IMG_DECLARE(ui_img_chess_elephants_red_png);    // assets/Chess_Elephants_Red.png
LV_IMG_DECLARE(ui_img_chess_knights_red_png);    // assets/Chess_Knights_Red.png
LV_IMG_DECLARE(ui_img_chess_rooks_red_png);    // assets/Chess_Rooks_Red.png
LV_IMG_DECLARE(ui_img_chess_cannons_red_png);    // assets/Chess_Cannons_Red.png
LV_IMG_DECLARE(ui_img_chess_pawns_red_png);    // assets/Chess_Pawns_Red.png



LV_FONT_DECLARE(ui_font_Black);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
