// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen_login
void ui_Screen_login_screen_init(void);
extern lv_obj_t * ui_Screen_login;
extern lv_obj_t * ui_Container_login_menu;
void ui_event_Username_login(lv_event_t * e);
extern lv_obj_t * ui_Username_login;
void ui_event_Password_login(lv_event_t * e);
extern lv_obj_t * ui_Password_login;
void ui_event_Button_login(lv_event_t * e);
extern lv_obj_t * ui_Button_login;
extern lv_obj_t * ui_Label_dummy;
void ui_event_Button_go_register(lv_event_t * e);
extern lv_obj_t * ui_Button_go_register;
extern lv_obj_t * ui_Label_dummy1;
extern lv_obj_t * ui_label_login_title;
extern lv_obj_t * ui_Keyboard_login;
extern lv_obj_t * ui_Container_login_success;
extern lv_obj_t * ui_Panel_login_success;
extern lv_obj_t * ui_Label_login_success;
extern lv_obj_t * ui_Container_login_fail;
extern lv_obj_t * ui_Panel_login_fail;
extern lv_obj_t * ui_Label_login_fail;
// SCREEN: ui_Screen_register
void ui_Screen_register_screen_init(void);
extern lv_obj_t * ui_Screen_register;
extern lv_obj_t * ui_Container_register_menu;
void ui_event_Username_register(lv_event_t * e);
extern lv_obj_t * ui_Username_register;
void ui_event_Password_register(lv_event_t * e);
extern lv_obj_t * ui_Password_register;
void ui_event_Button_register(lv_event_t * e);
extern lv_obj_t * ui_Button_register;
extern lv_obj_t * ui_Label_dummy3;
extern lv_obj_t * ui_Label_register_title;
extern lv_obj_t * ui_Keyboard_register;
void ui_event_Button_back_login_screen(lv_event_t * e);
extern lv_obj_t * ui_Button_back_login_screen;
extern lv_obj_t * ui_Label_dummy4;
extern lv_obj_t * ui_Container_register_success;
extern lv_obj_t * ui_Panel_register_success;
extern lv_obj_t * ui_Label_register_success;
extern lv_obj_t * ui_Container_register_fail;
extern lv_obj_t * ui_Panel_register_fail;
extern lv_obj_t * ui_Label_register_fail;
// SCREEN: ui_Screen_main_menu
void ui_Screen_main_menu_screen_init(void);
extern lv_obj_t * ui_Screen_main_menu;
extern lv_obj_t * ui_Container_screen_main_menu;
extern lv_obj_t * ui_Label3;
void ui_event_Button_back_login_screen2(lv_event_t * e);
extern lv_obj_t * ui_Button_back_login_screen2;
extern lv_obj_t * ui_Label_dummy5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Black);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
