// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Text_clean(lv_event_t * e);
void User_login(lv_event_t * e);
void User_register(lv_event_t * e);
void Create_Room_Handler(lv_event_t * e);
void event_button_exit(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
