// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: lvglUITest

#include "ui.h"

void my_button(lv_event_t * e)
{
	// Your code here
	printf("lvgl按钮点击\n");
}
