// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void User_login(lv_event_t * e)
{
	// Your code here
}

void User_register(lv_event_t * e)
{
	// Your code here
}
