// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_main_menu_screen_init(void)
{
    ui_Screen_main_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_main_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_screen_main_menu = lv_obj_create(ui_Screen_main_menu);
    lv_obj_remove_style_all(ui_Container_screen_main_menu);
    lv_obj_set_width(ui_Container_screen_main_menu, 800);
    lv_obj_set_height(ui_Container_screen_main_menu, 480);
    lv_obj_set_align(ui_Container_screen_main_menu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_screen_main_menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container_screen_main_menu);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label3, "当前在线人数：%	房间数：%	");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_back_login_screen2 = lv_btn_create(ui_Screen_main_menu);
    lv_obj_set_width(ui_Button_back_login_screen2, 60);
    lv_obj_set_height(ui_Button_back_login_screen2, 40);
    lv_obj_set_x(ui_Button_back_login_screen2, -10);
    lv_obj_set_y(ui_Button_back_login_screen2, -10);
    lv_obj_set_align(ui_Button_back_login_screen2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button_back_login_screen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_back_login_screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_dummy5 = lv_label_create(ui_Button_back_login_screen2);
    lv_obj_set_width(ui_Label_dummy5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_dummy5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_dummy5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_dummy5, "返回");
    lv_obj_set_style_text_font(ui_Label_dummy5, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen_main_menu);
    lv_obj_set_width(ui_Panel2, 500);
    lv_obj_set_height(ui_Panel2, 400);
    lv_obj_set_x(ui_Panel2, 20);
    lv_obj_set_y(ui_Panel2, 20);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Screen_main_menu);
    lv_obj_set_width(ui_Button4, 160);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, -50);
    lv_obj_set_align(ui_Button4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "创建房间");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen_main_menu);
    lv_obj_set_width(ui_Button5, 160);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 59);
    lv_obj_set_align(ui_Button5, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "加入房间");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button_back_login_screen2, ui_event_Button_back_login_screen2, LV_EVENT_ALL, NULL);

}
