// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_match_screen_init(void)
{
    ui_Screen_match = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_match, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen_match);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 800);
    lv_obj_set_height(ui_Container1, 480);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_chessboard = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image_chessboard, &ui_img_chessboard_png);
    lv_obj_set_width(ui_Image_chessboard, LV_SIZE_CONTENT);   /// 435
    lv_obj_set_height(ui_Image_chessboard, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image_chessboard, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image_chessboard, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_chessboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Chess_King_Black = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Chess_King_Black, &ui_img_chess_king_black_png);
    lv_obj_set_width(ui_Image_Chess_King_Black, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Chess_King_Black, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Chess_King_Black, 2);
    lv_obj_set_y(ui_Image_Chess_King_Black, 205);
    lv_obj_set_align(ui_Image_Chess_King_Black, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Chess_King_Black, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Chess_King_Black, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Mandarins_Black_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Mandarins_Black_Left, &ui_img_chess_mandarins_black_png);
    lv_obj_set_width(ui_Image_Mandarins_Black_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Mandarins_Black_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Mandarins_Black_Left, -44);
    lv_obj_set_y(ui_Image_Mandarins_Black_Left, 205);
    lv_obj_set_align(ui_Image_Mandarins_Black_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Mandarins_Black_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Mandarins_Black_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Mandarins_Black_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Mandarins_Black_Right, &ui_img_chess_mandarins_black_png);
    lv_obj_set_width(ui_Image_Mandarins_Black_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Mandarins_Black_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Mandarins_Black_Right, 48);
    lv_obj_set_y(ui_Image_Mandarins_Black_Right, 205);
    lv_obj_set_align(ui_Image_Mandarins_Black_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Mandarins_Black_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Mandarins_Black_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Elephants_Black_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Elephants_Black_Left, &ui_img_chess_elephants_black_png);
    lv_obj_set_width(ui_Image_Elephants_Black_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Elephants_Black_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Elephants_Black_Left, -90);
    lv_obj_set_y(ui_Image_Elephants_Black_Left, 205);
    lv_obj_set_align(ui_Image_Elephants_Black_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Elephants_Black_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Elephants_Black_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Elephants_Black_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Elephants_Black_Right, &ui_img_chess_elephants_black_png);
    lv_obj_set_width(ui_Image_Elephants_Black_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Elephants_Black_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Elephants_Black_Right, 94);
    lv_obj_set_y(ui_Image_Elephants_Black_Right, 205);
    lv_obj_set_align(ui_Image_Elephants_Black_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Elephants_Black_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Elephants_Black_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Knights_Black_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Knights_Black_Left, &ui_img_chess_knights_black_png);
    lv_obj_set_width(ui_Image_Knights_Black_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Knights_Black_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Knights_Black_Left, -136);
    lv_obj_set_y(ui_Image_Knights_Black_Left, 205);
    lv_obj_set_align(ui_Image_Knights_Black_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Knights_Black_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Knights_Black_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Knights_Black_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Knights_Black_Right, &ui_img_chess_knights_black_png);
    lv_obj_set_width(ui_Image_Knights_Black_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Knights_Black_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Knights_Black_Right, 140);
    lv_obj_set_y(ui_Image_Knights_Black_Right, 205);
    lv_obj_set_align(ui_Image_Knights_Black_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Knights_Black_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Knights_Black_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Rooks_Black_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Rooks_Black_Left, &ui_img_chess_rooks_black_png);
    lv_obj_set_width(ui_Image_Rooks_Black_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Rooks_Black_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Rooks_Black_Left, -182);
    lv_obj_set_y(ui_Image_Rooks_Black_Left, 205);
    lv_obj_set_align(ui_Image_Rooks_Black_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Rooks_Black_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Rooks_Black_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Rooks_Black_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Rooks_Black_Right, &ui_img_chess_rooks_black_png);
    lv_obj_set_width(ui_Image_Rooks_Black_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Rooks_Black_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Rooks_Black_Right, 186);
    lv_obj_set_y(ui_Image_Rooks_Black_Right, 205);
    lv_obj_set_align(ui_Image_Rooks_Black_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Rooks_Black_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Rooks_Black_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Cannons_Black_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Cannons_Black_Left, &ui_img_chess_cannons_black_png);
    lv_obj_set_width(ui_Image_Cannons_Black_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Cannons_Black_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Cannons_Black_Left, -136);
    lv_obj_set_y(ui_Image_Cannons_Black_Left, 113);
    lv_obj_set_align(ui_Image_Cannons_Black_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Cannons_Black_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Cannons_Black_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Cannons_Black_Left, 1);

    ui_Image_Cannons_Black_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Cannons_Black_Right, &ui_img_chess_cannons_black_png);
    lv_obj_set_width(ui_Image_Cannons_Black_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Cannons_Black_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Cannons_Black_Right, 140);
    lv_obj_set_y(ui_Image_Cannons_Black_Right, 113);
    lv_obj_set_align(ui_Image_Cannons_Black_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Cannons_Black_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Cannons_Black_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Pawns_Black1 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Black1, &ui_img_chess_pawns_black_png);
    lv_obj_set_width(ui_Image_Pawns_Black1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Black1, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Black1, -182);
    lv_obj_set_y(ui_Image_Pawns_Black1, 67);
    lv_obj_set_align(ui_Image_Pawns_Black1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Black1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Black1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Pawns_Black2 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Black2, &ui_img_chess_pawns_black_png);
    lv_obj_set_width(ui_Image_Pawns_Black2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Black2, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Black2, -90);
    lv_obj_set_y(ui_Image_Pawns_Black2, 67);
    lv_obj_set_align(ui_Image_Pawns_Black2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Black2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Black2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Pawns_Black3 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Black3, &ui_img_chess_pawns_black_png);
    lv_obj_set_width(ui_Image_Pawns_Black3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Black3, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Black3, 2);
    lv_obj_set_y(ui_Image_Pawns_Black3, 67);
    lv_obj_set_align(ui_Image_Pawns_Black3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Black3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Black3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Pawns_Black4 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Black4, &ui_img_chess_pawns_black_png);
    lv_obj_set_width(ui_Image_Pawns_Black4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Black4, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Black4, 94);
    lv_obj_set_y(ui_Image_Pawns_Black4, 67);
    lv_obj_set_align(ui_Image_Pawns_Black4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Black4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Black4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Pawns_Black5 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Black5, &ui_img_chess_pawns_black_png);
    lv_obj_set_width(ui_Image_Pawns_Black5, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Black5, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Black5, 186);
    lv_obj_set_y(ui_Image_Pawns_Black5, 67);
    lv_obj_set_align(ui_Image_Pawns_Black5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Black5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Black5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_General_Red = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_General_Red, &ui_img_chess_general_red_png);
    lv_obj_set_width(ui_Image_General_Red, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_General_Red, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_General_Red, 2);
    lv_obj_set_y(ui_Image_General_Red, -209);
    lv_obj_set_align(ui_Image_General_Red, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_General_Red, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_General_Red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_General_Red, 1800);

    ui_Image_Image_Mandarins_Red_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Image_Mandarins_Red_Left, &ui_img_chess_mandarins_red_png);
    lv_obj_set_width(ui_Image_Image_Mandarins_Red_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Image_Mandarins_Red_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Image_Mandarins_Red_Left, -44);
    lv_obj_set_y(ui_Image_Image_Mandarins_Red_Left, -208);
    lv_obj_set_align(ui_Image_Image_Mandarins_Red_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Image_Mandarins_Red_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Image_Mandarins_Red_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Image_Mandarins_Red_Left, 1800);

    ui_Image_Image_Mandarins_Red_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Image_Mandarins_Red_Right, &ui_img_chess_mandarins_red_png);
    lv_obj_set_width(ui_Image_Image_Mandarins_Red_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Image_Mandarins_Red_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Image_Mandarins_Red_Right, 48);
    lv_obj_set_y(ui_Image_Image_Mandarins_Red_Right, -208);
    lv_obj_set_align(ui_Image_Image_Mandarins_Red_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Image_Mandarins_Red_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Image_Mandarins_Red_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Image_Mandarins_Red_Right, 1800);

    ui_Image_Elephants_Red_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Elephants_Red_Left, &ui_img_chess_elephants_red_png);
    lv_obj_set_width(ui_Image_Elephants_Red_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Elephants_Red_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Elephants_Red_Left, -90);
    lv_obj_set_y(ui_Image_Elephants_Red_Left, -209);
    lv_obj_set_align(ui_Image_Elephants_Red_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Elephants_Red_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Elephants_Red_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Elephants_Red_Left, 1800);

    ui_Image_Elephants_Red_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Elephants_Red_Right, &ui_img_chess_elephants_red_png);
    lv_obj_set_width(ui_Image_Elephants_Red_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Elephants_Red_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Elephants_Red_Right, 94);
    lv_obj_set_y(ui_Image_Elephants_Red_Right, -209);
    lv_obj_set_align(ui_Image_Elephants_Red_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Elephants_Red_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Elephants_Red_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Elephants_Red_Right, 1800);

    ui_Image_Knights_Red_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Knights_Red_Left, &ui_img_chess_knights_red_png);
    lv_obj_set_width(ui_Image_Knights_Red_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Knights_Red_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Knights_Red_Left, -136);
    lv_obj_set_y(ui_Image_Knights_Red_Left, -209);
    lv_obj_set_align(ui_Image_Knights_Red_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Knights_Red_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Knights_Red_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Knights_Red_Left, 1800);

    ui_Image_Knights_Red_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Knights_Red_Right, &ui_img_chess_knights_red_png);
    lv_obj_set_width(ui_Image_Knights_Red_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Knights_Red_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Knights_Red_Right, 140);
    lv_obj_set_y(ui_Image_Knights_Red_Right, -209);
    lv_obj_set_align(ui_Image_Knights_Red_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Knights_Red_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Knights_Red_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Knights_Red_Right, 1800);

    ui_Image_Rooks_Red_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Rooks_Red_Left, &ui_img_chess_rooks_red_png);
    lv_obj_set_width(ui_Image_Rooks_Red_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Rooks_Red_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Rooks_Red_Left, -182);
    lv_obj_set_y(ui_Image_Rooks_Red_Left, -209);
    lv_obj_set_align(ui_Image_Rooks_Red_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Rooks_Red_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Rooks_Red_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Rooks_Red_Left, 1800);

    ui_Image_Rooks_Red_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Rooks_Red_Right, &ui_img_chess_rooks_red_png);
    lv_obj_set_width(ui_Image_Rooks_Red_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Rooks_Red_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Rooks_Red_Right, 186);
    lv_obj_set_y(ui_Image_Rooks_Red_Right, -209);
    lv_obj_set_align(ui_Image_Rooks_Red_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Rooks_Red_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Rooks_Red_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Rooks_Red_Right, 1800);

    ui_Image_Cannons_Red_Left = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Cannons_Red_Left, &ui_img_chess_cannons_red_png);
    lv_obj_set_width(ui_Image_Cannons_Red_Left, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Cannons_Red_Left, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Cannons_Red_Left, -136);
    lv_obj_set_y(ui_Image_Cannons_Red_Left, -117);
    lv_obj_set_align(ui_Image_Cannons_Red_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Cannons_Red_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Cannons_Red_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Cannons_Red_Left, 1800);

    ui_Image_Cannons_Red_Right = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Cannons_Red_Right, &ui_img_chess_cannons_red_png);
    lv_obj_set_width(ui_Image_Cannons_Red_Right, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Cannons_Red_Right, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Cannons_Red_Right, 140);
    lv_obj_set_y(ui_Image_Cannons_Red_Right, -117);
    lv_obj_set_align(ui_Image_Cannons_Red_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Cannons_Red_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Cannons_Red_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Cannons_Red_Right, 1800);

    ui_Image_Pawns_Red1 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Red1, &ui_img_chess_pawns_red_png);
    lv_obj_set_width(ui_Image_Pawns_Red1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Red1, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Red1, -182);
    lv_obj_set_y(ui_Image_Pawns_Red1, -71);
    lv_obj_set_align(ui_Image_Pawns_Red1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Red1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Red1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Pawns_Red1, 1800);

    ui_Image_Pawns_Red2 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Red2, &ui_img_chess_pawns_red_png);
    lv_obj_set_width(ui_Image_Pawns_Red2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Red2, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Red2, -90);
    lv_obj_set_y(ui_Image_Pawns_Red2, -71);
    lv_obj_set_align(ui_Image_Pawns_Red2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Red2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Red2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Pawns_Red2, 1800);

    ui_Image_Pawns_Red3 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Red3, &ui_img_chess_pawns_red_png);
    lv_obj_set_width(ui_Image_Pawns_Red3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Red3, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Red3, 2);
    lv_obj_set_y(ui_Image_Pawns_Red3, -71);
    lv_obj_set_align(ui_Image_Pawns_Red3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Red3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Red3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Pawns_Red3, 1800);

    ui_Image_Pawns_Red4 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Red4, &ui_img_chess_pawns_red_png);
    lv_obj_set_width(ui_Image_Pawns_Red4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Red4, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Red4, 94);
    lv_obj_set_y(ui_Image_Pawns_Red4, -71);
    lv_obj_set_align(ui_Image_Pawns_Red4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Red4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Red4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Pawns_Red4, 1800);

    ui_Image_Pawns_Red5 = lv_img_create(ui_Image_chessboard);
    lv_img_set_src(ui_Image_Pawns_Red5, &ui_img_chess_pawns_red_png);
    lv_obj_set_width(ui_Image_Pawns_Red5, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image_Pawns_Red5, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image_Pawns_Red5, 186);
    lv_obj_set_y(ui_Image_Pawns_Red5, -71);
    lv_obj_set_align(ui_Image_Pawns_Red5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pawns_Red5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Pawns_Red5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image_Pawns_Red5, 1800);

    ui_Button3 = lv_btn_create(ui_Screen_match);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_align(ui_Button3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_Screen_match);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_align(ui_Button6, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "认输");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

}
