// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_login_screen_init(void)
{
    ui_Screen_login = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_login_menu = lv_obj_create(ui_Screen_login);
    lv_obj_remove_style_all(ui_Container_login_menu);
    lv_obj_set_width(ui_Container_login_menu, 800);
    lv_obj_set_height(ui_Container_login_menu, 480);
    lv_obj_set_align(ui_Container_login_menu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_login_menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Username_login = lv_textarea_create(ui_Container_login_menu);
    lv_obj_set_width(ui_Username_login, 200);
    lv_obj_set_height(ui_Username_login, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Username_login, 0);
    lv_obj_set_y(ui_Username_login, -25);
    lv_obj_set_align(ui_Username_login, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Username_login, 16);
    lv_textarea_set_placeholder_text(ui_Username_login, "账号");
    lv_textarea_set_one_line(ui_Username_login, true);
    lv_obj_set_style_text_font(ui_Username_login, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Password_login = lv_textarea_create(ui_Container_login_menu);
    lv_obj_set_width(ui_Password_login, 200);
    lv_obj_set_height(ui_Password_login, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Password_login, 0);
    lv_obj_set_y(ui_Password_login, 25);
    lv_obj_set_align(ui_Password_login, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Password_login, 16);
    lv_textarea_set_placeholder_text(ui_Password_login, "密码");
    lv_textarea_set_one_line(ui_Password_login, true);
    lv_textarea_set_password_mode(ui_Password_login, true);
    lv_obj_set_style_text_font(ui_Password_login, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button_login = lv_btn_create(ui_Container_login_menu);
    lv_obj_set_width(ui_Button_login, 90);
    lv_obj_set_height(ui_Button_login, 40);
    lv_obj_set_x(ui_Button_login, -50);
    lv_obj_set_y(ui_Button_login, 75);
    lv_obj_set_align(ui_Button_login, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_login, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_dummy = lv_label_create(ui_Button_login);
    lv_obj_set_width(ui_Label_dummy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_dummy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_dummy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_dummy, "登录");
    lv_obj_set_style_text_color(ui_Label_dummy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_dummy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_dummy, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_go_register = lv_btn_create(ui_Container_login_menu);
    lv_obj_set_width(ui_Button_go_register, 90);
    lv_obj_set_height(ui_Button_go_register, 40);
    lv_obj_set_x(ui_Button_go_register, 50);
    lv_obj_set_y(ui_Button_go_register, 75);
    lv_obj_set_align(ui_Button_go_register, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_go_register, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_go_register, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_dummy1 = lv_label_create(ui_Button_go_register);
    lv_obj_set_width(ui_Label_dummy1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_dummy1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_dummy1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_dummy1, "注册");
    lv_obj_set_style_text_font(ui_Label_dummy1, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_login_title = lv_label_create(ui_Screen_login);
    lv_obj_set_width(ui_label_login_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_login_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_login_title, 0);
    lv_obj_set_y(ui_label_login_title, -70);
    lv_obj_set_align(ui_label_login_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_login_title, "欢迎进入在线对战系统");
    lv_obj_set_style_text_font(ui_label_login_title, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard_login = lv_keyboard_create(ui_Screen_login);
    lv_obj_set_width(ui_Keyboard_login, 800);
    lv_obj_set_height(ui_Keyboard_login, 190);
    lv_obj_set_align(ui_Keyboard_login, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard_login, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Container_login_success = lv_obj_create(ui_Screen_login);
    lv_obj_remove_style_all(ui_Container_login_success);
    lv_obj_set_width(ui_Container_login_success, 800);
    lv_obj_set_height(ui_Container_login_success, 480);
    lv_obj_set_align(ui_Container_login_success, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_login_success, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container_login_success, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container_login_success, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_login_success = lv_obj_create(ui_Container_login_success);
    lv_obj_set_width(ui_Panel_login_success, 240);
    lv_obj_set_height(ui_Panel_login_success, 50);
    lv_obj_set_align(ui_Panel_login_success, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_login_success, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_login_success = lv_label_create(ui_Panel_login_success);
    lv_obj_set_width(ui_Label_login_success, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_login_success, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_login_success, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_login_success, "登录成功，正在进入系统...");
    lv_obj_set_style_text_font(ui_Label_login_success, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_login_fail = lv_obj_create(ui_Screen_login);
    lv_obj_remove_style_all(ui_Container_login_fail);
    lv_obj_set_width(ui_Container_login_fail, 800);
    lv_obj_set_height(ui_Container_login_fail, 480);
    lv_obj_set_align(ui_Container_login_fail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container_login_fail, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container_login_fail, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container_login_fail, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container_login_fail, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_login_fail = lv_obj_create(ui_Container_login_fail);
    lv_obj_set_width(ui_Panel_login_fail, 240);
    lv_obj_set_height(ui_Panel_login_fail, 50);
    lv_obj_set_align(ui_Panel_login_fail, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_login_fail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_login_fail = lv_label_create(ui_Panel_login_fail);
    lv_obj_set_width(ui_Label_login_fail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_login_fail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_login_fail, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_login_fail, "登录失败，请重新输入！");
    lv_obj_set_style_text_font(ui_Label_login_fail, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Username_login, ui_event_Username_login, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Password_login, ui_event_Password_login, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_login, ui_event_Button_login, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_go_register, ui_event_Button_go_register, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_login, ui_event_Screen_login, LV_EVENT_ALL, NULL);

}
