// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: lvglUITest

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loginMain = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_loginMain);
    lv_obj_set_width(ui_loginMain, 363);
    lv_obj_set_height(ui_loginMain, 196);
    lv_obj_set_x(ui_loginMain, 8);
    lv_obj_set_y(ui_loginMain, -29);
    lv_obj_set_align(ui_loginMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_loginMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_loginMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_loginMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_username = lv_textarea_create(ui_loginMain);
    lv_obj_set_width(ui_username, lv_pct(100));
    lv_obj_set_height(ui_username, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_username, -67);
    lv_obj_set_y(ui_username, 1);
    lv_obj_set_align(ui_username, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_username, "username");
    lv_obj_set_style_bg_color(ui_username, lv_color_hex(0xE21313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_username, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_username, lv_color_hex(0x3812DC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_username, 255, LV_PART_MAIN | LV_STATE_CHECKED);



    ui_password = lv_textarea_create(ui_loginMain);
    lv_obj_set_width(ui_password, lv_pct(100));
    lv_obj_set_height(ui_password, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_password, -65);
    lv_obj_set_y(ui_password, -108);
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_password, "password");
    lv_textarea_set_one_line(ui_password, true);
    lv_textarea_set_password_mode(ui_password, true);
    lv_obj_set_style_bg_color(ui_password, lv_color_hex(0xA51919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_loginBt = lv_btn_create(ui_loginMain);
    lv_obj_set_height(ui_loginBt, 32);
    lv_obj_set_width(ui_loginBt, lv_pct(100));
    lv_obj_set_x(ui_loginBt, 5);
    lv_obj_set_y(ui_loginBt, 94);
    lv_obj_set_align(ui_loginBt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginBt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_loginBt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loginBt, lv_color_hex(0x21CF8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loginBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonLabel = lv_label_create(ui_loginBt);
    lv_obj_set_width(ui_buttonLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_buttonLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_buttonLabel, -1);
    lv_obj_set_y(ui_buttonLabel, 0);
    lv_obj_set_align(ui_buttonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_buttonLabel, "login");
    lv_obj_set_style_text_color(ui_buttonLabel, lv_color_hex(0xF10B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_buttonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_buttonLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_buttonLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_buttonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 82);
    lv_obj_set_y(ui_Button2, 58);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "登录");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -112);
    lv_obj_set_y(ui_Button4, 56);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "注册");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_loginBt, ui_event_loginBt, LV_EVENT_ALL, NULL);

}
