// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_register_screen_init(void)
{
    ui_Screen_register = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_register, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_register_menu = lv_obj_create(ui_Screen_register);
    lv_obj_remove_style_all(ui_Container_register_menu);
    lv_obj_set_width(ui_Container_register_menu, 800);
    lv_obj_set_height(ui_Container_register_menu, 480);
    lv_obj_set_align(ui_Container_register_menu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_register_menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Username_register = lv_textarea_create(ui_Container_register_menu);
    lv_obj_set_width(ui_Username_register, 200);
    lv_obj_set_height(ui_Username_register, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Username_register, 0);
    lv_obj_set_y(ui_Username_register, -25);
    lv_obj_set_align(ui_Username_register, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Username_register, 16);
    lv_textarea_set_placeholder_text(ui_Username_register, "账号");
    lv_textarea_set_one_line(ui_Username_register, true);
    lv_obj_set_style_text_font(ui_Username_register, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Password_register = lv_textarea_create(ui_Container_register_menu);
    lv_obj_set_width(ui_Password_register, 200);
    lv_obj_set_height(ui_Password_register, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Password_register, 0);
    lv_obj_set_y(ui_Password_register, 25);
    lv_obj_set_align(ui_Password_register, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Password_register, 16);
    lv_textarea_set_placeholder_text(ui_Password_register, "密码");
    lv_textarea_set_one_line(ui_Password_register, true);
    lv_textarea_set_password_mode(ui_Password_register, true);
    lv_obj_set_style_text_font(ui_Password_register, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button_register = lv_btn_create(ui_Container_register_menu);
    lv_obj_set_width(ui_Button_register, 200);
    lv_obj_set_height(ui_Button_register, 40);
    lv_obj_set_x(ui_Button_register, 0);
    lv_obj_set_y(ui_Button_register, 75);
    lv_obj_set_align(ui_Button_register, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_register, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_register, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_dummy3 = lv_label_create(ui_Button_register);
    lv_obj_set_width(ui_Label_dummy3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_dummy3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_dummy3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_dummy3, "注册");
    lv_obj_set_style_text_font(ui_Label_dummy3, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_register_title = lv_label_create(ui_Container_register_menu);
    lv_obj_set_width(ui_Label_register_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_register_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_register_title, 0);
    lv_obj_set_y(ui_Label_register_title, -70);
    lv_obj_set_align(ui_Label_register_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_register_title, "请输入注册信息：");
    lv_obj_set_style_text_font(ui_Label_register_title, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard_register = lv_keyboard_create(ui_Container_register_menu);
    lv_obj_set_width(ui_Keyboard_register, 800);
    lv_obj_set_height(ui_Keyboard_register, 190);
    lv_obj_set_align(ui_Keyboard_register, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard_register, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Button_back_login_screen = lv_btn_create(ui_Container_register_menu);
    lv_obj_set_width(ui_Button_back_login_screen, 60);
    lv_obj_set_height(ui_Button_back_login_screen, 40);
    lv_obj_set_x(ui_Button_back_login_screen, -10);
    lv_obj_set_y(ui_Button_back_login_screen, -10);
    lv_obj_set_align(ui_Button_back_login_screen, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button_back_login_screen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_back_login_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_dummy4 = lv_label_create(ui_Button_back_login_screen);
    lv_obj_set_width(ui_Label_dummy4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_dummy4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_dummy4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_dummy4, "返回");
    lv_obj_set_style_text_font(ui_Label_dummy4, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_register_success = lv_obj_create(ui_Screen_register);
    lv_obj_remove_style_all(ui_Container_register_success);
    lv_obj_set_width(ui_Container_register_success, 800);
    lv_obj_set_height(ui_Container_register_success, 480);
    lv_obj_set_align(ui_Container_register_success, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container_register_success, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container_register_success, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container_register_success, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container_register_success, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_register_success = lv_obj_create(ui_Container_register_success);
    lv_obj_set_width(ui_Panel_register_success, 240);
    lv_obj_set_height(ui_Panel_register_success, 50);
    lv_obj_set_align(ui_Panel_register_success, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_register_success, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_register_success = lv_label_create(ui_Panel_register_success);
    lv_obj_set_width(ui_Label_register_success, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_register_success, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_register_success, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_register_success, "注册成功，请重新登录！");
    lv_obj_set_style_text_font(ui_Label_register_success, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_register_fail = lv_obj_create(ui_Screen_register);
    lv_obj_remove_style_all(ui_Container_register_fail);
    lv_obj_set_width(ui_Container_register_fail, 800);
    lv_obj_set_height(ui_Container_register_fail, 480);
    lv_obj_set_align(ui_Container_register_fail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container_register_fail, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container_register_fail, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container_register_fail, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container_register_fail, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_register_fail = lv_obj_create(ui_Container_register_fail);
    lv_obj_set_width(ui_Panel_register_fail, 240);
    lv_obj_set_height(ui_Panel_register_fail, 50);
    lv_obj_set_align(ui_Panel_register_fail, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_register_fail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_register_fail = lv_label_create(ui_Panel_register_fail);
    lv_obj_set_width(ui_Label_register_fail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_register_fail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_register_fail, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_register_fail, "注册失败，账号已存在！");
    lv_obj_set_style_text_font(ui_Label_register_fail, &ui_font_Black, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Username_register, ui_event_Username_register, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Password_register, ui_event_Password_register, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_register, ui_event_Button_register, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_back_login_screen, ui_event_Button_back_login_screen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_register, ui_event_Screen_register, LV_EVENT_ALL, NULL);

}
